name: Check PR Source Branch

on:
  pull_request:
    branches:
      - develop

jobs:
  check_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if source branch is not main
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "main" ]; then
            echo "::set-output name=warning::true"
          else
            echo "::set-output name=warning::false"
          fi
        id: check_branch

      - name: Set status check
        if: steps.check_branch.outputs.warning == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'failure',
              description: 'Please use squash and merge',
              context: 'Squash Merge Warning'
            })
