name: Check Source Branch

on:
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Source Branch
        run: |
          SOURCE_BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH")
          if [ "$SOURCE_BRANCH" != "main" ]; then
            echo "::warning::Source branch is not main"
          fi
