name: CI/CD

on:
  workflow_call:

env:
  github-repo: transmitsecurity-dev/ido-sso-hosted

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.select-environment.outputs.environment }}
    steps:
      - name: Select environment to use
        id: select-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "{environment}={prod}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "{environment}={stg}" >> $GITHUB_OUTPUT
          else
            echo "{environment}={dev}" >> $GITHUB_OUTPUT
          fi
