name: Init

on:
  workflow_call:
    outputs:
      environment:
        description: "The selected environment"
        value: ${{ jobs.setup-environment.outputs.environment }}

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.select-environment.outputs.environment }}
    steps:
      - name: Select environment to use
        id: select-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "environment=stg" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
      - name: Echo selected environment
        run: |
          echo "Selected environment: ${{ steps.select-environment.outputs.environment }}"
