name: CI/CD

on:
  workflow_call:

env:
  github-repo: transmitsecurity-dev/ido-sso-hosted

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Select environment to use
        id: select-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "ENVIRONMENT=stg" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          fi
